apiVersion: k3d.io/v1alpha2 
kind: Simple
name: lab
servers: 1 
agents: 3 
image: rancher/k3s:v1.20.4-k3s1
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
options:
  k3d: 
    wait: true
    timeout: "60s"
  k3s: 
    extraServerArgs: 
      - --no-deploy=traefik
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true 
