apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-corpora-docker-image-from-git-source
spec:
  params:
    - name: pathToDockerFile
      type: string
      default: $(resources.inputs.corpora-source.path)/apps/corpora/Dockerfile
    - name: pathToContext
      type: string
      default: $(resources.inputs.corpora-source.path)/apps/corpora
  resources:
    inputs:
      - name: corpora-source
        type: git
    outputs:
      - name: corpora-image 
        type: image
  steps:
    - name: dump
      image: busybox
      command: ["ls", "-gAlFh", "/root/"]
    - name: dumpb
      image: busybox
      command: ["ls", "-gAlFh", "/root/.docker/"]
    - name: dumpc
      image: busybox
      command: ["ls", "-gAlFh", "/root/.docker/config.json"]
    - name: dumpd
      image: busybox
      command: ["cat", "/root/.docker/config.json"]
    - name: build
      image: gcr.io/kaniko-project/executor:latest
      command:
      - /kaniko/executor
      args:
      - --context=$(params.pathToContext)
      - --dockerfile=$(params.pathToDockerFile)
      - --destination=$(resources.outputs.corpora-image.url)


