apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-corpora-docker-image-from-git-source
spec:
  params:
    - name: pathToDockerFile
      type: string
      default: $(resources.inputs.corpora-source.path)/apps/corpora/Dockerfile
    - name: pathToContext
      type: string
      default: $(resources.inputs.corpora-source.path)/apps/corpora
  resources:
    inputs:
      - name: corpora-source
        type: git
    outputs:
      - name: corpora-image 
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.16.0
      env:
        - name: "DOCKER_HUB_CREDENTIALS"
          value: bddh
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.pathToDockerFile)
        - --destination=$(resources.outputs.corpora-image.url)
        - --context=$(params.pathToContext)
