apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-corpora-docker-image-from-git-source
spec:
  params:
    - name: pathToDockerFile
      type: string
      default: $(resources.inputs.corpora-source.path)/apps/corpora/Dockerfile
    - name: pathToContext
      type: string
      default: $(resources.inputs.corpora-source.path)/apps/corpora
  resources:
    inputs:
      - name: corpora-source
        type: git
    outputs:
      - name: corpora-image 
        type: image
  steps:
    - name: echo
      image: busybox
      command: ["echo", "$(params.pathToDockerFile)"]
    - name: pwd
      image: busybox
      command: ["pwd"]
    - name: ls 
      image: busybox
      command: ["ls", "-gAlFh", "~/"]
    - name: dump-config
      image: busybox
      command: ["cat", "~/.docker/config.json"]
